import {Service} from '../enums/service.enum';
import {BillingCycle} from '../enums/billing-cycle.enum';
import {Status} from '../enums/status.enum';
import {UserGroup} from '../enums/user-group.enum';
import {AvailabilityBlock} from './availability-block.model';

export class Contact {
  id?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone_number?: string;
  service?: Service;
  status?: Status;
  billing_cycle?: BillingCycle;
  cc_authorization_received?: boolean;
  twenty_five_deducted?: boolean;
  special_circumstance?: string;
  scholarship_state?: string;
  invoice_Month?: string;
  date_funds_requested_by_btc?: Date;
  date_funds_requested_by_family?: Date;
  invoice_number?: string;
  invoice_paid_date?: Date;
  inquiry_received?: Date;
  inquiry_note_from_parent?: string;
  consult_date?: Date;
  twenty_five_received?: boolean;
  scholarship_student?: boolean;
  scholarship_name?: string;
  trial_date?: Date;
  registration_sent?: Date;
  registration_received?: Date;
  title?: string;
  currently_accepting_students?: boolean;
  availability?: AvailabilityBlock[];
  zoom_link?: string;
  hourly_rate?: number;
  hiring_inquiry_received?: Date;
  interview_offer_sent?: Date;
  interview_scheduled?: Date;
  offer_sent?: Date;
  onboarding_paperwork_received?: Date;
  training_completed?: Date;
  user_profile_created?: boolean;
  user_group?: UserGroup;
}
